
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.PrintStream;
import javax.imageio.ImageIO;
import java.io.*;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shais8602
 */
public class RP extends javax.swing.JFrame {
File database;
    Scanner indata;
    PrintStream outdata;


    private void captureComponent(Component jFrame1) {
        // This is creating a screenshot for the frame1 and then it opens the print menu
        Rectangle rect = jFrame1.getBounds();

        try {
            String format = "png";
            String fileName = jFrame1.getName() + "." + format;
            BufferedImage captureImage =
                    new BufferedImage(rect.width - 207, rect.height - 87,
                    BufferedImage.TYPE_INT_ARGB);
            jFrame1.paint(captureImage.getGraphics());

            ImageIO.write(captureImage, format, new File(fileName));
            Desktop.getDesktop().print(new File(fileName));
            System.out.printf("The screenshot of %s was saved!", jFrame1.getName());
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }

    /**
     * Creates new form RP
     */
    public RP() throws FileNotFoundException {
        // This is preety much setting the demsenions in which we want it to open as
        initComponents();
        this.setSize(1170, 680);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dim = tk.getScreenSize();
        int xPos = (dim.width / 2) - (this.getWidth() / 2);
        int yPos = (dim.height / 2) - (this.getHeight() / 2);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        database = new File("database");
        outdata = new PrintStream(new FileOutputStream(database, true));
        indata = new Scanner(database);
        
        loadFiles();

    }
     private void loadFiles() {
        while(indata.hasNext()) {
            jTextArea2.append(indata.nextLine()+"\n");
            
        } 
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextArea5 = new javax.swing.JTextArea();
        jTextArea6 = new javax.swing.JTextArea();
        jTextArea7 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swagpic.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jFrame1.getContentPane().add(jLabel20, java.awt.BorderLayout.PAGE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(577, 648, 0, 0);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Course 2:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 250, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Course 3:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 350, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Course 4:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 460, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Course 1:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 140, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Mark 2:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 240, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Mark 3:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 350, 60, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Mark 4:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 460, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Mark 1:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 130, 60, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Teacher Comment 2:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 240, 130, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Teacher Comment 3:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 350, 130, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Teacher Comment 4:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 460, 130, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Teacher Comment 1:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 130, 130, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Last Name:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(190, 100, 70, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 100, 90, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("First Name:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 100, 70, 20);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 100, 80, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Calculate Average");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 580, 130, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Average:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(180, 580, 50, 20);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(400, 270, 60, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(40, 370, 230, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(40, 480, 230, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(40, 160, 230, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(240, 570, 90, 30);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(400, 380, 60, 30);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(400, 490, 60, 30);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(400, 160, 60, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Report Card Pro");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 20, 120, 20);

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(40, 270, 230, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Student Database");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(970, 100, 100, 15);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Add Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(890, 570, 110, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Delete Student");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1010, 570, 120, 23);

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12);
        jTextField12.setBounds(960, 160, 170, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(530, 380, 410, 60);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton1.setText("Print");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(360, 580, 110, 23);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextArea5);
        jTextArea5.setBounds(530, 490, 410, 60);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextArea6);
        jTextArea6.setBounds(530, 160, 410, 60);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextArea7);
        jTextArea7.setBounds(530, 270, 410, 60);

        jButton3.setText("Search:");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(960, 130, 80, 23);

        jButton5.setText("Help");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1020, 60, 90, 23);

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(960, 200, 168, 350);

        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(510, 580, 90, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1141, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // we set variables and got the numbers from the textfield
        int average;
        if (!jTextField10.getText().isEmpty()) {
            num1 = Integer.parseInt(jTextField10.getText());
        } else {
            num1 = 0;
        }
        if (!jTextField3.getText().isEmpty()) {
            num2 = Integer.parseInt(jTextField3.getText());
        } else {
            num2 = 0;
        }
        if (!jTextField8.getText().isEmpty()) {
            num3 = Integer.parseInt(jTextField8.getText());
        } else {
            num3 = 0;
        }
        if (!jTextField9.getText().isEmpty()) {
            num4 = Integer.parseInt(jTextField9.getText());
        } else {
            num4 = 0;
        }
// by pressing the average button it added up all the numbers, dividing by 4 and set it to average textfield
        average = (num1 + num2 + num3 + num4) / 4;
        jTextField7.setText(String.valueOf(average));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        captureComponent(this);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String search = (jTextField12.getText());

            String inFileName = search;
            File inFile = new File(inFileName);
            Scanner in = new Scanner(inFile);
            String lastnum = in.next();
            jTextField2.setText(lastnum);
            String name = in.next();
            jTextField1.setText(name);
            String num1 = in.next();
            jTextField10.setText(num1);
            String num2 = in.next();
            jTextField3.setText(num2);
            String num3 = in.next();
            jTextField8.setText(num3);
            String num4 = in.next();
            jTextField9.setText(num4);
            String course1 = in.next();
            jTextField6.setText(course1);
            String cousre2 = in.next();
            jTextField11.setText(cousre2);
            String cousre3 = in.next();
            jTextField4.setText(cousre3);
            String cousre4 = in.next();
            jTextField5.setText(cousre4);
            String average = in.next();
            jTextField7.setText(String.valueOf(average));
            String comment1 = in.next();
            jTextArea6.setText(comment1);
            String comment2 = in.next();
            jTextArea7.setText(comment2);
            String comment3 = in.next();
            jTextArea1.setText(comment3);
            String comment4 = in.next();
            jTextArea5.setText(comment4);

        } catch (FileNotFoundException ex) {
        }

    }//GEN-LAST:event_jButton3ActionPerformed
    int num1;
    int num2;
    int num3;
    int num4;
    String course1, course2, course3, course4;
    String comment1, comment2, comment3, comment4;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // First we need to determine the last name and name to make a file with that certain name 
        // this will make it easier to find 
        

        
        String lastname = (jTextField2.getText());
        String name = (jTextField1.getText());
        String names = (name + " " + lastname);
        
        // Now we make that certain file inorder to store information
        
        String outFileName = names;
        File outFile = new File(outFileName);
        
        if (new File(outFileName).exists() && !new File(outFileName).isDirectory()) {} 
        
        else {
        
            jTextArea2.append(name+" "+lastname);
            
            jTextArea2.append("\n");
            outdata.println(name+" "+lastname);
            
        try (PrintStream out = new PrintStream(outFile)) {
            
            // we need to check if the textfield has anything in it, if it doesnt then set it as null or 0
            
            if (!jTextField10.getText().isEmpty()) {
                num1 = Integer.parseInt(jTextField10.getText());
            } else {
                num1 = 0;
            }
            
            if (!jTextField3.getText().isEmpty()) {
                num2 = Integer.parseInt(jTextField3.getText());
            } else {
                num2 = 0;
            }
            
            if (!jTextField8.getText().isEmpty()) {
                num3 = Integer.parseInt(jTextField8.getText());
            } else {
                num3 = 0;
            }
            
            
            if (!jTextField9.getText().isEmpty()) {
                num4 = Integer.parseInt(jTextField9.getText());
            } else {
                num4 = 0;
            }
            
            if (!jTextField6.getText().isEmpty()) {
                course1 = (jTextField6.getText());
            } else {
                course1 = null;
            }
            
            if (!jTextField11.getText().isEmpty()) {
                course2 = (jTextField11.getText());
            } else {
                course2 = null;
            }
            
            if (!jTextField4.getText().isEmpty()) {
                course3 = (jTextField4.getText());
            } else {
                course3 = null;
            }
            
            if (!jTextField5.getText().isEmpty()) {
                course4 = (jTextField5.getText());
            } else {
                course4 = null;
            }
            
            if (!jTextArea6.getText().isEmpty()) {
                comment1 = (jTextArea6.getText());
            } else {
                comment1 = null;
            }
            
            if (!jTextArea7.getText().isEmpty()) {
                comment2 = (jTextArea7.getText());

            } else {
                comment2 = null;
            }
            
            if (!jTextArea1.getText().isEmpty()) {
                comment3 = (jTextArea1.getText());
            } else {
                comment3 = null;
            }
            
            if (!jTextArea5.getText().isEmpty()) {
                comment4 = (jTextArea5.getText());
            } else {
                comment4 = null;
            }
            
            // Now we print all of it      
            out.println(lastname);
            out.println(name);
            out.println(num1);
            out.println(num2);
            out.println(num3);
            out.println(num4);
            out.println(course1);
            out.println(course2);
            out.println(course3);
            out.println(course4);
            out.println((num1 + num2 + num3 + num4) / 4);
            out.println(comment1);
            out.println(comment2);
            out.println(comment3);
            out.println(comment4);
            
        } catch (FileNotFoundException ex) {
        }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // make a new jFrame
        jFrame1.show(true);
        quickFix(jFrame1);
        jFrame1.setSize(1100, 850);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dim = tk.getScreenSize();
        int xPos = (dim.width / 2) - (this.getWidth() / 2);
        int yPos = (dim.height / 2) - (this.getHeight() / 2);
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String names = (jTextField12.getText());
        // Currently being built !!!
        File file = new File(names);
                file.delete();
                System.out.println("The file has been deleted ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // setting up a file name that would be appropriate and efficent
        String lastname = (jTextField2.getText());
        String name = (jTextField1.getText());
        String names = (name + " " + lastname);
        // using that certain file now to store new information
         String outFileName = names;
        File outFile = new File(outFileName);
        try (PrintStream out = new PrintStream(outFile)) {
            
            // we need to check if the textfield has anything in it, if it doesnt then set it as null or 0
            
            if (!jTextField10.getText().isEmpty()) {
                num1 = Integer.parseInt(jTextField10.getText());
            } else {
                num1 = 0;
            }
            
            if (!jTextField3.getText().isEmpty()) {
                num2 = Integer.parseInt(jTextField3.getText());
            } else {
                num2 = 0;
            }
            
            if (!jTextField8.getText().isEmpty()) {
                num3 = Integer.parseInt(jTextField8.getText());
            } else {
                num3 = 0;
            }
            
            
            if (!jTextField9.getText().isEmpty()) {
                num4 = Integer.parseInt(jTextField9.getText());
            } else {
                num4 = 0;
            }
            
            if (!jTextField6.getText().isEmpty()) {
                course1 = (jTextField6.getText());
            } else {
                course1 = null;
            }
            
            if (!jTextField11.getText().isEmpty()) {
                course2 = (jTextField11.getText());
            } else {
                course2 = null;
            }
            
            if (!jTextField4.getText().isEmpty()) {
                course3 = (jTextField3.getText());
            } else {
                course3 = null;
            }
            
            if (!jTextField5.getText().isEmpty()) {
                course4 = (jTextField5.getText());
            } else {
                course4 = null;
            }
            
            if (!jTextArea6.getText().isEmpty()) {
                comment1 = (jTextArea6.getText());
            } else {
                comment1 = null;
            }
            
            if (!jTextArea7.getText().isEmpty()) {
                comment2 = (jTextArea7.getText());

            } else {
                comment2 = null;
            }
            
            if (!jTextArea1.getText().isEmpty()) {
                comment3 = (jTextArea1.getText());
            } else {
                comment3 = null;
            }
            
            if (!jTextArea5.getText().isEmpty()) {
                comment4 = (jTextArea5.getText());
            } else {
                comment4 = null;
            }
            
            // Now we print all of the new information into the file   
            out.println(lastname);
            out.println(name);
            out.println(num1);
            out.println(num2);
            out.println(num3);
            out.println(num4);
            out.println(course1);
            out.println(course2);
            out.println(course3);
            out.println(course4);
            out.println((num1 + num2 + num3 + num4) / 4);
            out.println(comment1);
            out.println(comment2);
            out.println(comment3);
            out.println(comment4);
            
        } catch (FileNotFoundException ex) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RP().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(RP.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    private void quickFix(JFrame h) {
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }
}
